<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4Y2kxD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4Y2kxD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG4Y2kxD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG4Y2kxD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG4Y2kxD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G4Y2kxD',
    'container.build_id' => 'd969658a',
    'container.build_time' => 1566571002,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4Y2kxD');
