<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZBi5muG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZBi5muG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZBi5muG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZBi5muG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZBi5muG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZBi5muG',
    'container.build_id' => 'ecd7b689',
    'container.build_time' => 1566571105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZBi5muG');
